{
 "title": "Teamspeak 3",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "virtualserver",
    "query": "label_values(ts3_serverinfo_online, virtualserver)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online Virtual Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(ts3_serverinfo_online)" }
   ]
  },
  {
   "title": "Channels Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum(ts3_serverinfo_channels_online{virtualserver=~\"${virtualserver}\"})"
    }
   ]
  },
  {
   "title": "Exporter Error Rate (last 5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(ts3_exporter_data_model_refresh_errors_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime in Seconds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "repeat": "virtualserver",
   "targets": [
    { "expr": "ts3_serverinfo_uptime", "legendFormat": "{{virtualserver}}" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Clients online",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(ts3_serverinfo_control_bytes_sent_total[5m])",
     "legendFormat": "{{virtualserver}} control bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_control_bytes_received_total[5m])",
     "legendFormat": "{{virtualserver}} control bytes received"
    },
    {
     "expr": "rate(ts3_serverinfo_file_transfer_bytes_sent_total[5m])",
     "legendFormat": "{{virtualserver}} file transfer bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_file_transfer_bytes_received_total[5m])",
     "legendFormat": "{{virtualserver}} file transfer bytes received"
    },
    {
     "expr": "rate(ts3_serverinfo_keepalive_bytes_sent_total[5m])",
     "legendFormat": "{{virtualserver}} keepalive bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_keepalive_bytes_received_total[5m])",
     "legendFormat": "{{virtualserver}} keepalive bytes received"
    },
    {
     "expr": "rate(ts3_serverinfo_speech_bytes_sent_total[5m])",
     "legendFormat": "{{virtualserver}} speech bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_speech_bytes_received_total[5m])",
     "legendFormat": "{{virtualserver}} speech bytes received"
    }
   ]
  },
  {
   "title": "Clients online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (virtualserver) (ts3_serverinfo_query_client_connections)",
     "legendFormat": "{{virtualserver}} QueryClients"
    },
    {
     "expr": "max by (virtualserver) (ts3_serverinfo_client_connections)",
     "legendFormat": "{{virtualserver}} Clients"
    }
   ]
  }
 ]
}